### ISSUE TITLE
Stellar Staging - When confirming a transaction the keyboard stays open, hides confirm button on smaller devices.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_wallet#103]
**Repro steps**
1) Send transaction
2) Go to confirm screen

**Expected Result**
Keyboard is closed

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/80981039-addd8280-8e29-11ea-8747-59e09187aecd.png)

**System Info**

**Comment by tobiaschielens** [comment]
Blocked by: https://github.com/threefoldtech/3Bot_connect/issues/96
