### ISSUE TITLE
Trades done on stellar exchanges are not reflected in the wallet transaction history

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_wallet#147]
**Repro steps**
1) Buy some TFTA for XLM on interstellar
2) Check the wallet balance update
3) Check the transaction history for TFTA

Some more examples of trades not showing
https://stellar.expert/explorer/public/tx/130126217599840256#130126217599840257
https://stellar.expert/explorer/public/tx/130126148880412672#130126148880412673

**Expected Result**
The transaction history should add up to the total balance

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/85674512-31e31680-b6c5-11ea-97bf-5b7359134cdd.png)
![image](https://user-images.githubusercontent.com/59569757/85674545-38718e00-b6c5-11ea-9e11-a1b9b4b73ac9.png)

**System Info**

**Comment by JonasWijne** [comment]
payments and trades are seperate from each other
