### ISSUE TITLE
staging 3bot connect not working as it should after a testnet reset

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/threefold_wallet#158]
- stays hanging on initializing wallet
- where can the wallet be downloaded? Is that in manual?
- how do people know they have the right version, is that documented in the manual

## remark

- version nr should be 2.2... something because is now for 2.2 version of grid

**Comment by xmonader** [comment]
moved to the right repo

**Comment by ken-de-moor** [comment]
We should look into how to automatically fix this everytime a reset happens.

If the reset times are predefined can we force a reload or clear pkid data every reset?

**Comment by tobiaschielens** [comment]
@despiegk Can you send me your staging name and seed phrase in telegram? Then we can debug this further. My telegram handle is @tchielens

**Comment by despiegk** [comment]
for testnet:

**Comment by despiegk** [comment]
testnet version only as apk for android
people need to know what the status us of testnet, and how to deal with this

**Comment by ken-de-moor** [comment]
We now use actual production TFT even for VDC testnet, staging version is only for internal testers who need to work their own way around testnet resets.

Issue will be closed
