### ISSUE TITLE
It should be possible to buy TFT with BTC, in the app

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_wallet#184]
- [x] Add a buy screen 
   - [x] Minimum x TFT to purchase 
   - [x] Calculate price based on set BTC to TFT ratio
   - [x] Make it possible for user to input amount to buy, and BTC it will cost
- [x] Implement Stellar Dex
- [x] Implement trades in stellar Crypto

- [x] Implement Kraken API

**Comment by JonasWijne** [comment]
Several options: 
- add completely different `screen` in the app
- add screen in wallet
  -  different wallet exclusively for BTC
  - BTC as another asset for the accounts

**Comment by JonasWijne** [comment]
@robvanmieghem 
services: 
1. add btc trustline 
2. btc/ tft rate with arbitraition protection
3. account that returns tfts when btc is send

**Comment by ken-de-moor** [comment]
@JonasWijne spoke to Rob
- Need to Ask for legal ticket. ( Terms & Conditions )

**Comment by sasha-astiadi** [comment]
removed - [ ] Create trade service ( Rob ) ( TBD )
