### ISSUE TITLE
We need to know the exact fee to use.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_wallet#188]
Currently we handle any fee 0.1 TFT or smaller.

We would need an API where we can determine the actual fee to use, because in the app it is hardcoded at 0.1 Fee.

The app should then read out this API and determine exactly what fee to display to the user.

This would be required for FreeTFT, TFT and TFTA, as these legacy tokens still exist.

Continuation UX issue from https://github.com/threefoldtech/threefold_connect/issues/207

**Comment by sasha-astiadi** [comment]
add: max fee 0.1 , temporary solutioon for this sprint. 2.5

**Comment by sasha-astiadi** [comment]
fee is 0.01, closing

**Comment by ken-de-moor** [comment]
This is not fixed, we implemented a workaround and this ticket is for the correct solution.
