### ISSUE TITLE
- We need a legal section for depositing BTC.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_wallet#191]
- [ ] Users are required to accept these terms & conditions before they can deposit BTC
 - [ ] Terms & Conditions to be provided still.

**Comment by ken-de-moor** [comment]
hi @sasha-astiadi , we had a meeting with Rob to implement Buying TFT for BTC in the app. We need terms and conditions specifically for this scenario that users need to accept before depositing BTC. Do you know who can provide this?

**Comment by sasha-astiadi** [comment]
will research on this thanks ken. @ken-de-moor

**Comment by sasha-astiadi** [comment]
which part of spec is it? now?
@ken-de-moor i guess we need to spec as well for tfconnect improvements

**Comment by ken-de-moor** [comment]
Closing as it is no longer required as we're not adding BTC yet for now.
