### ISSUE TITLE
Implement BTC support

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_wallet#200]
- [x] Fund BTC trustline - Self Funding​​​​​​​
- [x] Fund BTC trustline - Fallback​​​​​​​
- [x] Add asset card for BTC
- [x] Add BTC in transactions​​​​​​​
- [x] Withdraw actual BTC
   - [x] Implement UI/UX in transfer
   - [x]  API implementation ( Crypto Anchor )
- [x] Deposit actual BTC
   - [x] API implementation ( Crypto Anchor )
   - [x] UI/UX deposit page
- [x] Transfer Stellar BTC
- [x] Integrate BTC transfer in current transaction
- [x] Terms and conditions​​​​​​​
- [x] Withdraw BTC Fee Funding ( Need Fee Rework to implement )

**Comment by ken-de-moor** [comment]
Put on pause

**Comment by sasha-astiadi** [comment]
need to be tested

**Comment by sasha-astiadi** [comment]
@gmachtel please give link on wiki here on legal / wallet btc use.

**Comment by sasha-astiadi** [comment]
live on staging: april 21 (approx.)

**Comment by sasha-astiadi** [comment]
https://threefold.io/info/threefold#/legal__terms_conditions_griduser 
@ken-de-moor
