### ISSUE TITLE
Importing a wallet without XLM shouldn't break the app and get user stuck in initializing.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_wallet#206]
Repro steps :

- Import a wallet
- Delete trustlines
- Merge account

=> Open app, stays stuck on initializing.

1) Optimal solution: simply make the import work entirely. Make it possible to see and manage the wallet, but transactions themselves fail due to no XLM.

2) Less optimal solution : Fail to import those wallets without XLM or put them in an error state so they can be deleted/removed automatically.

Currently it keeps the user stuck initializing, which is very bad since they can't access their otehr wallets either.

**Comment by xmonader** [comment]
original issue https://github.com/threefoldtech/threefold_wallet/issues/203

also reports from @pkgraz

**Comment by ken-de-moor** [comment]
There might be more cases than the tested variation, but it seems to be fixed for now. Will need actual validation of people with the issue in production as well to be 100% sure.

**Comment by Pkgraz** [comment]
When is TF wallet 2.7 due? I would like to test if the bug is gone

**Comment by ken-de-moor** [comment]
> When is TF wallet 2.7 due? I would like to test if the bug is gone

Hi @Pkgraz , we are currently blocked on launch due to a critical issue for BTC implementation. We could provide a beta production app if you want to test however. This would require you to delete your current production app and re-install from android APK. We can only offer this for Android.

We are going to look into doing the production update with all the BTC implementation removed for now, so we can launch teh fix earlier. We can't keep being blocked by the other implementations, we need this fix live.

**Comment by Pkgraz** [comment]
either way is fine for me, many thanks Ken

**Comment by ken-de-moor** [comment]
Fixed, validated in prod 2.7.0

**Comment by Pkgraz** [comment]
Many thanks - just verified - my TF Connect app opens the Wallet correctly and instantly - showing now a failed imported wallet (the one that caused the issue before)
