### ISSUE TITLE
Binance Smart Chain transfer

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/threefold_wallet#213]
Create a UI extension where the user can create a transfer to a BEP20 address. (similar to ERC20).

This transfer should:
- Send the amount to a be defined bridge stellar address
- Convert the BEP20 address to a memo text

Added by Ken : 

- Add a new button under the transaction screen called "Advanced"
- Advanced section opens a new subscreen.
- There is a dropdown which allows you to select a specific advanced transaction.
- For now the only one that should be in here is "Binance smartchain"
- This one should be selected by default.
- User gets two inputs : Address and Amount of TFT to send.
- When submitting there is a confirm screen with the following text "You are sending your TFT to the Binance smartchain, this is another blockchain. This is an advanced user flow, make sure you know what you are doing!"
- Confirm/Cancel
- The whole memo translation thing and hardcoded address thing should just be done in the background, don't show it to the user.
- Make sure the predefined bridge stellar address is configurable
- Validate the input address so users are not inputting stellar addresses here ! Make sure they are specifically Binance smartchain addresses.

Use following for memo calculation : 

https://github.com/JimberSoftware/stellar-crypto/pull/16

**Comment by ken-de-moor** [comment]
@DylanVerstraete could you maybe include exactly the fields the user has to input?

For example : 

"Address" : <BEP20address>
"TFT" : <Amount of TFT to send>

I assume only those fields are needed, and the app can calculate everything else?

**Comment by DylanVerstraete** [comment]
Well you can't really do validation on the amount since that validation needs to come from the stellar wallet?

**Comment by DylanVerstraete** [comment]
Include where?

**Comment by ken-de-moor** [comment]
> Include where?

Discussed in telegram pms, added in original ticket.

**Comment by sasha-astiadi** [comment]
developed but not gonna bee used/disabled for now

**Comment by ken-de-moor** [comment]
Was shelved, will close as it'll probably return with entirely different specs if it's ever needed.
