### ISSUE TITLE
[Release Blocker] Need validation of all screens and texts.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_wallet#224]
- Important release with possible legal side effects, we need a careful review and texts provided.
- Current screenshots are provided to show implementation. All texts can and should still be changed. Please provide feedback and text on each screen before production rollout.

![image](https://user-images.githubusercontent.com/59569757/115454875-8e4d8e80-a221-11eb-9432-491ef75f0883.png)

![image](https://user-images.githubusercontent.com/59569757/115454903-94dc0600-a221-11eb-9153-73ae615186b4.png)

![image](https://user-images.githubusercontent.com/59569757/115454915-99082380-a221-11eb-93c7-4cb9414d5bfe.png)

![image](https://user-images.githubusercontent.com/59569757/115454937-9dccd780-a221-11eb-812a-e9d7f8dbf6d9.png)

![image](https://user-images.githubusercontent.com/59569757/115454963-a6251280-a221-11eb-8657-8066f7dc81d9.png)

![image](https://user-images.githubusercontent.com/59569757/115454988-acb38a00-a221-11eb-90d0-cbb42dc727a1.png)

![image](https://user-images.githubusercontent.com/59569757/115455008-b1783e00-a221-11eb-971e-bbb0949c14c7.png)

![image](https://user-images.githubusercontent.com/59569757/115455031-b76e1f00-a221-11eb-842f-d8424d9edda8.png)

**Comment by ken-de-moor** [comment]
@sasha-astiadi do you know who has the ownership to validate these and provide the correct texts? It's not something I can decide for myself.

Would also need a final link to use for the terms and conditions link. ( Currently https://threefold.io/info/threefold#/legal__terms_conditions_griduser ) - This does not yet mention anything about BTC being changed into Stellar BTC when you deposit them.

**Comment by sasha-astiadi** [comment]
tf connect staging app on android (download link) https://drive.google.com/file/d/1nRskDuQsCTpqASj1wzHxTMszBraKoawN/view?usp=sharing

**Comment by sasha-astiadi** [comment]
document for t&c is being reviewed.

**Comment by sasha-astiadi** [comment]
good to go.... t&c document comes later

**Comment by sasha-astiadi** [comment]
@JonasWijne 

- [ ] replace 'buy' with 'Trade'

- [ ] Trade Confirmation
By trading, you confirm that you agree with our [terms and conditions]link comes later

Price: (BTC / USD)
Amount: (BTC)
Total: (TFT)

'Confirm Trade'

**Comment by sasha-astiadi** [comment]
t&c link https://threefold.io/info/threefold#/legal__terms_conditions_griduser 
@JonasWijne 

will still be this link, we just change the content to include btc once validated
