### ISSUE TITLE
automatic TF Wallet Withdraw BTC back to BTC mainnet isn't working.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_wallet#234]
atm we do manual withdraw of btc. next step is to find a workaround to do it automatically.

- Withdraw BTC back to mainnet doesn't actually reward that BTC
- Goal address bc1qu2q9r2hlntznpefxwqlw9gf27mhxlf0xvaqajl )
- Stellar transaction on  https://stellar.expert/explorer/public/tx/151019631472136192#151019631472136194

Fintech LTD (Creators of cryptoanchor) have been contacted as no error is shown but the BTC is gone ( 107$ worth )

**Comment by robvanmieghem** [comment]
@ken-de-moor I think the easiest solution is to to buy 1 xlm on the stellar dex ( if the user has no xlm already) and don't use the  tx funding service

**Comment by sasha-astiadi** [comment]
@JonasWijne @ken-de-moor @robvanmieghem what can we do to make it clear to user for this risk

**Comment by sasha-astiadi** [comment]
put it for later since its not the most urgent one to do

**Comment by ken-de-moor** [comment]
This won't be possible to implement at all, fintech is refusing any contact requests. We will need another implementation entirely.
