### ISSUE TITLE
Improve texts for TFT/BTC rollout

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_wallet#236]
Ticket bundling the feedback for texts provided in TFT/BTC  flows. Bundle for a smaller update later.

| Current                                | Proposed Change                                                                                                                        | Feedback From |
|----------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|---------------|
| A high withdraw fee may be applicable. | "Please note that due to the Stellar/BTC bridge functionalities, withdrawing BTC may have a higher fee than a regular BTC transaction" | Maximilian    |
|                                        | Add help button with link to https://wiki.threefold.io/#/threefold__threefold_connect_btc                                                                                                                                       |  Kristof De Spiegeleer             |
|                                        |                                                                                                                                        |               |

**Comment by maximilianrang** [comment]
"Please note that due to the Stellar/BTC bridge functionalities, withdrawing BTC may have a higher fee than a regular BTC transaction" 
This works!
