### ISSUE TITLE
tf wallet text improvements

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/threefold_wallet#239]
- [x] vesting: 
Transfer TFT to the vesting wallet to start vesting

- [x] All area on header (text and arrow) should be clickable, not only the arrow

- [x]  Capital I (Transfer Info)

- [x]  BTC Activation:
     - [x] Activate BTC Asset 
     - [x] Remove the description texts and status
     - [x] Conditions with big C, move period
     - [x] By clicking 'Activate', I acknowledge [ThreeFold's BTC Asset Guide](https://wiki.threefold.io/#/threefold__threefold_connect_btc_asset_guide), and agree to the [Terms and Conditions](https://wiki.threefold.io/#/legal__legal)
     
    
     
     - [x] dialogue: Successfully activated BTC Asset
     - [x] dialogue: Activating BTC  Asset (BTC always capital -> BTC)
     
     
     
- [x]  deposit btc
      - [ ] Remove status
      - [ ] Send BTC to the following address by clicking the copy icon or scanning the QR code below
      - [ ] Successfully copied address to clipboard

- [x] order confirmation
    - [x] Nav bar Title: Confirm Order
    - [x] Title : Order Confirmation
    - [x] Make a new div, dialogue style: 
            - [ ] Title: Order Summary
            - [ ] BTC Amount:  amount BTC (amount) USD
            - [ ] Sum: est. (amount) TFT
            - [ ] Max Price: (amount) BTC (amount) USD / 1 TFT
            - [ ] Confirm Order
     

- [x] trading
     - [x] Wallet Name:
     - [x] Stay on this screen to continue trading 
     - [x] remove trading....
     - [x] BTC Amount:  amount BTC (amount) USD
     - [x] Sum: est. (amount) TFT
     - [x] Max Price: (amount) BTC (amount) USD / 1 TFT
     
- [x] vesting tab
   - [x] Vested TFT capital V, add TFT
 

- [x] update the wiki https://wiki.threefold.io/#/threefold__threefold_connect_btc_asset_guide

**Comment by jdelrue** [comment]
@sasha-astiadi why hide devview? This is a feature that has solved numerous cases of problems with users. We need it. Users dont hit the the details 5 times by accident I think?

**Comment by sasha-astiadi** [comment]
@jdelrue if you resolve "All area on header (text and arrow) should be clickable, not only the arrow" then it can stay... because me and sam clicked the header numerous times (next to arrow), and it didn't go back to previous page, showing us devview instead... so I think that not be user friendly
.

**Comment by JonasWijne** [comment]
implemented on v2.8.0 check staging

**Comment by ken-de-moor** [comment]
@sasha-astiadi @gmachtel Text changes are live on staging.

There is one direct link to https://wiki.threefold.io/#/threefold__threefold_connect_btc_asset_guide

If this one is live, can you let us know and we can deploy to production. Or should we deploy with that link still going to a 404?

**Comment by sasha-astiadi** [comment]
pr request on wiki need someone to verify and bring it to master so we can laiunch the new wallet to prod today https://github.com/threefoldfoundation/info_threefold/pull/48

**Comment by sasha-astiadi** [comment]
wallet guide is live @jdelrue @JonasWijne @ken-de-moor https://wiki.threefold.io/#/threefold__threefold_connect_btc_asset_guide
