### ISSUE TITLE
Increase clickable area in the wallet

### ISSUE THREAD

**Issue by Vilnite** [threefoldtech/threefold_wallet#243]
Got a feedback from an important investor that we need to make wider area (arrow + word) clickable in the wallet:

![IMAGE 2021-05-24 11:11:10](https://user-images.githubusercontent.com/20182572/119310406-beed7180-bc80-11eb-8bbd-564e487c8e1e.jpg)

Please update!

**Comment by ken-de-moor** [comment]
Ready on staging, waiting on https://github.com/threefoldtech/threefold_wallet/issues/239 to deploy
