### ISSUE TITLE
Conversion error on the app

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_wallet#249]
Receiving multiple messages on support chat about an error when trying to open the wallet in the app. 'conversion mistake'. Tried to reproduce, working for me. Asked for screenshots and extra information.

**Comment by sabrinasadik** [comment]
![69174bc18445f05ed705b2d053adaf767b206ec0](https://user-images.githubusercontent.com/31733464/122606443-3a242680-d079-11eb-9d5a-d862c73195c5.jpg)

Android Samsung Galaxy S10

**Comment by sabrinasadik** [comment]
Message from user: Of course it doesn't helped to close and open my wallet again. Further i closed
the app and my tasks, restarted my phone, deinstalled the app and installed it
again. But today luck isn't at my side

**Comment by ken-de-moor** [comment]
Need error logs, please press the E on error 5 times and copy the logs.

**Comment by sabrinasadik** [comment]
[
0 : {
timestamp : Mon, 21 Jun 2021 10:48:33 GMT,
message : startedWallet,
ctx : [VAR: UNDEFINED],
level : INFO,
},
1 : {
timestamp : Mon, 21 Jun 2021 10:48:44 GMT,
message : initialize,
ctx : [VAR: UNDEFINED],
level : INFO,
},
2 : {
timestamp : Mon, 21 Jun 2021 10:48:45 GMT,
message : initializeSingleAccount,
ctx : {
index : 0,
revine :
017ec3ce68979bf7b7ef76ede87542c49f4285f300b8cc1d288a5e4d0b32c08917ecb604ee275f,
stellar : GC6BBIV7XCGSZLHPZWM743CVJJTWEDW6W274WLJL5J62Y6JVYMQYOQ6M,
type : app,
},
level : INFO,
},
3 : {
timestamp : Mon, 21 Jun 2021 10:48:48 GMT,
message : error Something went wrong while fetching account,
ctx : {
e : NotFoundError: Not Found,
},
level : ERROR,
},
4 : {
timestamp : Mon, 21 Jun 2021 10:48:50 GMT,
message : error Something went wrong while generating account,
ctx : {
e : Error: Request failed with status code 400,
error :
/explorer/hashes/017ec3ce68979bf7b7ef76ede87542c49f4285f300b8cc1d288a5e4d0b32c08917ecb604ee275f:
GET: no content available (code: 204),
},
level : ERROR,
},
5 : {
timestamp : Mon, 21 Jun 2021 10:48:50 GMT,
message : error initializeImportedPkidAccounts,
ctx : {
error : Error: Tfchain address has 0 balance, no need to activate an account,
},
level : ERROR,
},
]

**Comment by ken-de-moor** [comment]
@JonasWijne major in prod, several users hitting this error on their wallet. Can you see anything in the logs?

**Comment by JonasWijne** [comment]
Its an error checking the stellar explorer

**Comment by sabrinasadik** [comment]
Any updates? It's urgent.

**Comment by ken-de-moor** [comment]
Problem is currently we are hitting an error flow that we were supposed to hit during the Rivine to stellar migration.

Fixing this would disable the rivine to stellar migration, and everyone who has not opened their wallet since the migration would lose their tokens. We need to rewrite the entire migration to fix this. :/

**Comment by sabrinasadik** [comment]
When is this being rewritten? We're getting complaints of conversion error so has some priority. Any ETA or workaround?

**Comment by sabrinasadik** [comment]
@sasha-astiadi is this done? So is the migration rewritten?

**Comment by sabrinasadik** [comment]
I need updates asap.

**Comment by JonasWijne** [comment]
we can manually fix the problem for people by funding their account with xlm and giving the right assets

**Comment by sabrinasadik** [comment]
Please check who had/has this problem and ask for their wallet address, @JonasWijne will fund it with xlm as a workaround for now

**Comment by FlorinaRogers** [comment]
@sabrinasadik 

Please find the wallet addresses of the 2 users facing this issue below:

User Malik — GC6BBIV7XCGSZLHPZWM743CVJJTWEDW6W274WLJL5J62Y6JVYMQYOQ6M

User Gary — GCGQXQZZNG7CI7IOYBJOK6YBW4VT36DUSDTQCPNJVWTU4HWD7B5CRRSX

**Comment by sabrinasadik** [comment]
@JonasWijne see Florina's comment - fix it manually pls as you said. This issue has been open since June 18th.

**Comment by FlorinaRogers** [comment]
@JonasWijne and @sasha-astiadi and @ken-de-moor 

Please give an update on this issue.

**Comment by sabrinasadik** [comment]
@nbabenko can you help here?

**Comment by jdelrue** [comment]
I funded the wallets, should be ok

**Comment by FlorinaRogers** [comment]
@jdelrue Both the users facing this issue are asking why is the wallet empty. Can you please let me know what you meant by funding the wallets so I can go back to my users and explain to them?

**Comment by jdelrue** [comment]
We funded the wallets with XLM so they work again, we did not give them any other currency or whatsoever. The problem should be fixed and thats it.

**Comment by FlorinaRogers** [comment]
@jdelrue You can close this issue
