### ISSUE TITLE
[Staging] Wallet stuck in initializing.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_wallet#251]
Completely new account, loads very long before returning an error.

[
    0 : {
        timestamp : Mon, 28 Jun 2021 15:53:40 GMT,
        message : startedWallet,
        ctx : [VAR: UNDEFINED],
        level : INFO,
    },
    1 : {
        timestamp : Mon, 28 Jun 2021 15:53:40 GMT,
        message : initialize,
        ctx : [VAR: UNDEFINED],
        level : INFO,
    },
    2 : {
        timestamp : Mon, 28 Jun 2021 15:53:41 GMT,
        message : error Something went wrong while fetching account,
        ctx : {
            e : NotFoundError: Not Found,
        },
        level : ERROR,
    },
    3 : {
        timestamp : Mon, 28 Jun 2021 15:53:54 GMT,
        message : initializeSingleAccount,
        ctx : {
            index : 0,
            revine : 01afe36df3318ecf2036239ee1a1c4ecf60838baa0c46c6d5e19e86b0001b67f73abfca52f1465,
            stellar : GCIOFCEBBQLTWVMYNWWWHQ7PM2H57AFU3MYCB6AZPCTHTYZS36QIRTCR,
            type : app,
        },
        level : INFO,
    },
    4 : {
        timestamp : Mon, 28 Jun 2021 15:55:09 GMT,
        message : error convertTfAccount failed,
        ctx : {
            error : Error: Request failed with status code 400,
        },
        level : ERROR,
    },
    5 : {
        timestamp : Mon, 28 Jun 2021 15:55:09 GMT,
        message : Conversion TF Account error ,
        ctx : {
            errorlog : Tfchain address has 0 balance, no need to activate an account,
        },
        level : ERROR,
    },
    6 : {
        timestamp : Mon, 28 Jun 2021 15:55:09 GMT,
        message : start Sms Flow,
        ctx : [VAR: UNDEFINED],
        level : INFO,
    },
    7 : {
        timestamp : Mon, 28 Jun 2021 15:55:09 GMT,
        message : init error,
        ctx : {
            error : function(){var e=[].slice.apply(arguments);return i.__new__(e)},
        },
        level : ERROR,
    },
]

**Comment by sasha-astiadi** [comment]
not reproducible, code rewriting will happen after new blockchain asset feature request and un-vesting feature request done

**Comment by ken-de-moor** [comment]
This issue was staging specific and is resolved there.
