### ISSUE TITLE
2.7 ui improvements - wallet

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtech/threefold_wallet#255]
The following improvements should be added to the wallet. 

transfer

- [x] ~~where is the back button on transfer~~  should not be there in the  payment view (since you're technically not in the wallet)

wallet

- [ ] where is vesting

success page

- [x] add icon
- [x] add title description
- [ ] add text and link to reserve digital twin page

**Comment by JonasWijne** [comment]
~~where is the back button on transfer~~  should not be there in the payment view (since you're technically not in the wallet)
