### ISSUE TITLE
Not all TFT's were converted when going to Stellar wallet

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_wallet#265]
User: Pierre (internal)
Old wallet address: 018f1db57fa2b5bbde751503219853910054e6ef8821512be8e5d389873d5343eabfad95d0a435
New wallet address: GD5UBZMGQYJLVXWBJRWOJYLFQVKTWBNCR7EHNUN3MCO3DY2UHPCI7VEL
1620831.0593357 TFT unlocked
894459.1425784 TFT locked on stellar
Missing around 800k tokens

**Comment by robvanmieghem** [comment]
@sabrinasadik This can be closed, right?

**Comment by sabrinasadik** [comment]
Yep, thanks for the reminder!
