### ISSUE TITLE
Fee to threefold is hardcoded 0.1

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/threefold_wallet#79]
Make the fee dynamic as this is hardcoded 0.1 of the payment currency

**Comment by ken-de-moor** [comment]
Closed and shelved as a hardcoded 0.1 TFT fee is what was decided on anyay.

**Comment by tobiaschielens** [comment]
Fees  wil be dynamic in the future

**Comment by tobiaschielens** [comment]
Currently implemented as >= will need to be imporved
![image](https://user-images.githubusercontent.com/17977313/108722638-aa83c680-7523-11eb-8e4b-936d1c02067f.png)
